name: Auto Unzip, Commit & Cleanup

# Trigger on push (when ZIP file uploaded) or manual run
on:
  push:
    paths:
      - "*.zip"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip-and-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Define ZIP file name
        id: vars
        run: |
          # 👇 Change only this line to your ZIP filename
          echo "ZIP_FILE=Render_bot_ready.zip" >> $GITHUB_ENV

      - name: Show detected ZIP file
        run: echo "Target ZIP is $ZIP_FILE"

      - name: Extract ZIP into repo root
        run: |
          set -e
          echo "Extracting: $ZIP_FILE"
          if [ ! -f "$ZIP_FILE" ]; then
            echo "❌ ZIP not found: $ZIP_FILE"
            exit 1
          fi

          rm -rf tmp_extract
          mkdir tmp_extract
          unzip -q "$ZIP_FILE" -d tmp_extract

          # Move contents (handles nested folder)
          first_dir=$(find tmp_extract -mindepth 1 -maxdepth 1 -type d | head -n 1 || true)
          if [ -n "$first_dir" ]; then
            echo "Detected top folder: $first_dir"
            shopt -s dotglob || true
            mv -f "$first_dir"/* .
          else
            mv -f tmp_extract/* .
          fi
          rm -rf tmp_extract

      - name: Remove original ZIP (cleanup)
        run: |
          echo "Removing ZIP: $ZIP_FILE"
          rm -f "$ZIP_FILE"
          git add -A

      - name: Commit & push extracted files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
            exit 0
          fi

          git commit -m "Auto extracted and cleaned ZIP: $ZIP_FILE"
          git push
